### ISSUE TITLE
Cant start py

### ISSUE THREAD

**Issue by ezequiel454** [smorano/stellar-horizon-exporter#1]
Error:

Traceback (most recent call last):
  File "stellar-horizon-exporter.py", line 7, in <module>
    from stellar_base.horizon import horizon_livenet
  File "/usr/local/lib/python3.6/site-packages/stellar_base/__init__.py", line 3, in <module>
    from .keypair import Keypair
  File "/usr/local/lib/python3.6/site-packages/stellar_base/keypair.py", line 8, in <module>
    from .utils import encode_check, StellarMnemonic, \
  File "/usr/local/lib/python3.6/site-packages/stellar_base/utils.py", line 14, in <module>
    from mnemonic import Mnemonic
ModuleNotFoundError: No module named 'mnemonic'

Any ideia ?

**Comment by ezequiel454** [comment]
I fix the error, but nothing working on port 9101.
